nginx:
  image: nginx:latest
  ports:
    - 80:80
    - 443:443
  links:
    - web:web
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf:ro

db:
  image: postgres:latest
  environment:
    POSTGRES_USER: {{ project_name }}
  env_file: .env

web:
  build: .
  links:
    - db:db
  environment:
    POSTGRES_HOST: db
    POSTGRES_USER: {{ project_name }}
  env_file: .env
  command: gunicorn -k gevent -b 0.0.0.0:8000 --access-logfile - --error-logfile - {{ project_name }}.wsgi
